import {test,expect} from '@playwright/test';
const start=async page=>{await page.goto('/builder.html');await page.waitForFunction(()=>window.playBuilder&&!window.playBuilder.busy);};
test('genuine custom recipes, deterministic shared playhead and authored undo',async({page})=>{
 await start(page);const proof=await page.evaluate(async()=>{const b=playBuilder;const before=JSON.stringify(b.compiled.play);b.seek(1.2);const time=b.session.clock.elapsed;await b.switchView('2d');const two=b.session.clock.elapsed;await b.switchView('3d');const three=b.session.clock.elapsed;await b.action('editShot',{field:'target.x',value:7});const changed=JSON.stringify(b.compiled.play)!==before;await b.action('selectShot',b.document.shots[2].id);await b.action('editShot',{field:'family',value:'drive'});const drive=b.compiled.play.steps[3].shot.type;await b.action('undo');return{time,two,three,changed,drive,restored:b.document.shots[2].family,valid:b.compiled.validShotCount};});
 expect(proof).toEqual({time:1.2,two:1.2,three:1.2,changed:true,drive:'drive',restored:'drop',valid:3});
});
test('court target picking round trips in both projections without moving the planner',async({page})=>{
 await start(page);for(const view of ['2d','3d']){await page.evaluate(async view=>{await playBuilder.switchView(view);await playBuilder.courtTools.bind();},view);const points=await page.evaluate(()=>({start:playBuilder.courtTools.project(playBuilder.selectedShot.target),end:playBuilder.courtTools.project({x:7,y:36})}));await page.mouse.move(points.start.x,points.start.y);await page.mouse.down();await page.mouse.move(points.end.x,points.end.y,{steps:8});await page.mouse.up();const target=await page.evaluate(()=>playBuilder.selectedShot.target);expect(target.x).toBeCloseTo(7,1);expect(target.y).toBeCloseTo(36,1);}
});
test('planner workspace, saved draft and loop hold survive view changes',async({page})=>{
 await start(page);const proof=await page.evaluate(async()=>{const b=playBuilder;const doc=JSON.stringify(b.document);b.seek(1);await b.setWorkspace('planner');b.board.updateTokenPosition(b.board.tokens.player1,4,-3);const planner=b.board.captureBoardState();await b.setWorkspace('builder');const time=b.session.clock.elapsed;await b.setWorkspace('planner');const restored=b.board.captureBoardState();await b.setWorkspace('builder');await b.action('title','My custom rally');await b.action('loop',true);b.session.clock.elapsed=b.session.duration;b.session.holding=true;b.session.holdElapsed=.4;await b.switchView(b.view==='3d'?'2d':'3d');return{same:JSON.stringify(restored)===JSON.stringify(planner),time,hold:b.session.holdElapsed,holding:b.session.holding,loop:b.session.loop,title:b.document.title};});
 expect(proof).toMatchObject({same:true,time:1,hold:.4,holding:true,loop:true,title:'My custom rally'});await page.reload();await page.waitForFunction(()=>window.playBuilder&&!playBuilder.busy);expect(await page.evaluate(()=>playBuilder.document.title)).toBe('My custom rally');
});
