import{test,expect}from'@playwright/test';
const open=async page=>{await page.goto('/');await page.waitForFunction(()=>window.playBuilder&&!playBuilder.busy);};
const menu=async(page,name)=>{const summary=page.locator('.builder-menu summary').filter({hasText:new RegExp(`^${name}$`)});await summary.click();return summary;};
const editShot=async page=>{const button=page.getByRole('button',{name:'Edit shot',exact:true});if(await button.isVisible())await button.click();};
const details=async page=>{const summary=page.getByText('Details · coordinates, contact, movement',{exact:true});if(!(await summary.locator('..').evaluate(node=>node.open)))await summary.click();};
test('authors a longer rally through real controls, saves copies, and reopens named work',async({page})=>{
 await open(page);await page.getByLabel('Play title').fill('Wide serve rally');await page.getByLabel('Play title').press('Tab');await editShot(page);await details(page);
 await page.getByLabel('Target width',{exact:true}).fill('7');await page.getByLabel('Target width',{exact:true}).press('Tab');
 await page.getByRole('button',{name:'3. Drop',exact:true}).click();await page.getByLabel('Shot family',{exact:true}).selectOption('drive');
 for(let i=0;i<3;i++)await page.getByRole('button',{name:'+ Add shot',exact:true}).click();
 expect(await page.evaluate(()=>playBuilder.document.shots.length)).toBe(6);
 const id=await page.evaluate(()=>playBuilder.document.id);await menu(page,'File');await page.getByRole('button',{name:'Save As',exact:true}).click();expect(await page.evaluate(()=>playBuilder.document.id)).not.toBe(id);
 await menu(page,'File');await page.getByRole('button',{name:'Open',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Wide serve rally',exact:true}).click();expect(await page.evaluate(()=>playBuilder.document.id)).toBe(id);expect(await page.evaluate(()=>playBuilder.document.shots[0].target.x)).toBe(7);
 await menu(page,'Plays');await page.getByRole('button',{name:'New Play',exact:true}).click();expect(await page.evaluate(()=>playBuilder.document.id)).not.toBe(id);expect(await page.evaluate(id=>playBuilder.store.open(id).shots.length,id)).toBe(6);
});
test('assistance is undoable and guides do not enable generated movement',async({page})=>{
 await open(page);const before=await page.evaluate(()=>JSON.stringify(playBuilder.compiled.play.steps));await page.getByRole('checkbox',{name:'Coverage Guides',exact:true}).check();expect(await page.evaluate(()=>playBuilder.document.assistance.autoShading)).toBe(false);expect(await page.evaluate(()=>JSON.stringify(playBuilder.compiled.play.steps))).toBe(before);
 await page.getByRole('checkbox',{name:'Auto Shading',exact:true}).check();expect(await page.evaluate(()=>JSON.stringify(playBuilder.compiled.play.steps))).not.toBe(before);await page.getByRole('button',{name:'Undo authored edit',exact:true}).click();expect(await page.evaluate(()=>playBuilder.document.assistance)).toMatchObject({autoShading:false,showGuides:true});
});
for(const[width,height]of[[1440,900],[768,1024],[1024,768],[390,844],[844,390],[320,568]])test(`default builder court and essential controls fit ${width}x${height}`,async({page})=>{
 await page.setViewportSize({width,height});await open(page);
 for(const name of ['Plays','File'])await expect(page.locator('.builder-menu summary').filter({hasText:new RegExp(`^${name}$`)})).toBeVisible();
 await menu(page,'Plays');for(const action of ['new','templates','workspace-planner','help']){const control=page.locator(`.builder-ui [data-action="${action}"]`).first();await expect(control).toBeVisible();const box=await control.boundingBox();expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(width+1);}await menu(page,'Plays');
 await menu(page,'File');for(const action of ['save-as','open','import-export']){const control=page.locator(`.builder-ui [data-action="${action}"]`).first();await expect(control).toBeVisible();const box=await control.boundingBox();expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(width+1);}await menu(page,'File');
 for(const action of ['play-pause','loop']){const control=page.locator(`.builder-ui [data-action="${action}"]`).first();await expect(control).toBeVisible();const box=await control.boundingBox();expect(box.x).toBeGreaterThanOrEqual(0);expect(box.y).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(width+1);expect(box.y+box.height).toBeLessThanOrEqual(height+1);}
 const canvas=await page.locator('#threeDCanvas canvas').boundingBox();expect(canvas.height).toBeGreaterThan(150);expect(canvas.width).toBeGreaterThan(250);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('emulated touch target placement at DPR2 and cancellation preserve authoring coordinates',async({browser})=>{const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,hasTouch:true});const page=await context.newPage();await open(page);await page.evaluate(()=>{playBuilder.courtTools.placing=true;playBuilder.courtTools.surface.addEventListener('pointerup',e=>window.actualTap=playBuilder.courtTools.unproject(e),{capture:true,once:true});});const p=await page.evaluate(()=>playBuilder.courtTools.project({x:6,y:37}));await page.touchscreen.tap(p.x,p.y);const target=await page.evaluate(()=>playBuilder.selectedShot.target);const actual=await page.evaluate(()=>window.actualTap);expect(target.x).toBeCloseTo(actual.x,8);expect(target.y).toBeCloseTo(actual.y,8);await page.evaluate(()=>{playBuilder.courtTools.placing=true;});await page.keyboard.press('Escape');expect(await page.evaluate(()=>playBuilder.courtTools.placing)).toBe(false);expect(await page.evaluate(()=>playBuilder.selectedShot.target)).toEqual(target);await context.close();});

test('committing a title does not swallow the immediate Save As click',async({page})=>{await open(page);await page.getByLabel('Play title').fill('First click copy');await menu(page,'File');await page.getByRole('button',{name:'Save As',exact:true}).click();expect(await page.evaluate(()=>playBuilder.document.title)).toBe('First click copy — copy');expect(await page.evaluate(()=>playBuilder.store.list().length)).toBe(2);});

test('builder help returns keyboard focus to its menu without changing the draft',async({page})=>{await open(page);const before=await page.evaluate(()=>JSON.stringify(playBuilder.document));const plays=await menu(page,'Plays');const help=page.getByRole('button',{name:'Help',exact:true});await help.click();await expect(page.locator('#infoModal')).toHaveClass(/active/);await page.keyboard.press('Escape');await expect(plays).toBeFocused();expect(await page.evaluate(()=>JSON.stringify(playBuilder.document))).toBe(before);});
test('200 percent text keeps transport and compact scene controls accessible',async({page})=>{await page.setViewportSize({width:390,height:844});await open(page);await page.evaluate(()=>{document.documentElement.style.fontSize='200%';playBuilder.render();});await expect(page.locator('body')).toHaveClass(/builder-large-text/);const play=page.getByRole('button',{name:'Play',exact:true});await play.scrollIntoViewIfNeeded();await expect(play).toBeVisible();expect(await page.evaluate(()=>document.querySelector('.builder-ui').scrollWidth<=innerWidth)).toBe(true);});

test('example file import is explicit and leaves the authoring controls usable',async({page})=>{await page.setViewportSize({width:844,height:390});await open(page);await menu(page,'File');await page.getByRole('button',{name:'Import / Export',exact:true}).click();await page.getByLabel('Choose JSON file').setInputFiles('docs/builder/examples/eight-shot-drive-drop.json');await expect(page.getByLabel('JSON backup')).toHaveValue(/eight-shot-drive-drop/);await page.getByRole('button',{name:'Import JSON',exact:true}).click();expect(await page.evaluate(()=>playBuilder.document.shots.length)).toBe(8);expect(await page.evaluate(()=>playBuilder.message)).not.toContain('malformed');const add=page.getByRole('button',{name:'+ Add shot',exact:true});await expect(add).toBeEnabled();const box=await add.boundingBox();expect(box.x+box.width).toBeLessThanOrEqual(844);await add.click();expect(await page.evaluate(()=>playBuilder.document.shots.length)).toBe(9);await editShot(page);const family=page.getByLabel('Shot family',{exact:true});await family.scrollIntoViewIfNeeded();await family.selectOption('drop');expect(await page.evaluate(()=>playBuilder.selectedShot.family)).toBe('drop');});

test('undoing an appended shot retains a valid editable selection',async({page})=>{await open(page);await page.getByRole('button',{name:'+ Add shot',exact:true}).click();await page.getByRole('button',{name:'Undo authored edit',exact:true}).click();expect(await page.evaluate(()=>Boolean(playBuilder.selectedShot))).toBe(true);await editShot(page);await details(page);await page.getByLabel('Target width',{exact:true}).fill('6');await page.getByLabel('Target width',{exact:true}).press('Tab');expect(await page.evaluate(()=>playBuilder.selectedShot.target.x)).toBe(6);});

test('shot details disclose precise coordinates and preserve an explicit manual pin',async({page})=>{await open(page);await editShot(page);await expect(page.getByLabel('Target width',{exact:true})).toBeHidden();await details(page);await expect(page.getByLabel('Target width',{exact:true})).toHaveAttribute('step','0.1');await page.getByLabel('Movement intent').selectOption('manual');await details(page);await page.getByLabel('Manual X').fill('8.4');await page.getByLabel('Manual X').press('Tab');await details(page);await page.getByLabel('Manual Y').fill('12.7');await page.getByLabel('Manual Y').press('Tab');await details(page);await page.getByRole('checkbox',{name:'Pin movement target'}).check();expect(await page.evaluate(()=>playBuilder.selectedShot.movement)).toMatchObject({intent:'manual',pinned:true,target:{x:8.4,y:12.7}});});

test('opening and closing the shot inspector changes neither source nor playhead',async({page})=>{await open(page);const before=await page.evaluate(()=>({source:JSON.stringify(playBuilder.document),time:playBuilder.session.clock.elapsed}));const toggle=page.getByRole('button',{name:'Edit shot',exact:true});await toggle.click();await page.getByRole('button',{name:'Collapse',exact:true}).click();expect(await page.evaluate(()=>({source:JSON.stringify(playBuilder.document),time:playBuilder.session.clock.elapsed}))).toEqual(before);});

test('a hidden target cannot intercept a playback gesture',async({page})=>{await open(page);await page.evaluate(async()=>{if(playBuilder.view!=='2d')await playBuilder.switchView('2d');playBuilder.play();});await expect.poll(()=>page.evaluate(()=>playBuilder.session.clock.elapsed)).toBeGreaterThan(0);const before=await page.evaluate(()=>({source:JSON.stringify(playBuilder.document),point:playBuilder.courtTools.project(playBuilder.selectedShot.target),time:playBuilder.session.clock.elapsed}));await page.mouse.click(before.point.x,before.point.y);await expect.poll(()=>page.evaluate(()=>playBuilder.session.clock.elapsed)).toBeGreaterThan(before.time);expect(await page.evaluate(()=>JSON.stringify(playBuilder.document))).toBe(before.source);});

for(const view of ['2d','3d'])test(`direct target drag preserves its grab offset in ${view}`,async({page})=>{await open(page);await page.evaluate(async view=>{if(playBuilder.view!==view)await playBuilder.switchView(view);},view);const points=await page.evaluate(()=>{const origin=playBuilder.courtTools.project(playBuilder.selectedShot.target);return{origin,start:{x:origin.x+8,y:origin.y+5},end:{x:origin.x+42,y:origin.y+23}};});const expected=await page.evaluate(({start,end})=>{const fake=(point)=>({clientX:point.x,clientY:point.y});const a=playBuilder.courtTools.unproject(fake(start)),b=playBuilder.courtTools.unproject(fake(end)),target=playBuilder.selectedShot.target;return{x:target.x+b.x-a.x,y:target.y+b.y-a.y};},{start:points.start,end:points.end});await page.mouse.move(points.start.x,points.start.y);await page.mouse.down();await page.mouse.move(points.end.x,points.end.y,{steps:6});await page.mouse.up();const actual=await page.evaluate(()=>playBuilder.selectedShot.target);expect(actual.x).toBeCloseTo(expected.x,6);expect(actual.y).toBeCloseTo(expected.y,6);});

test('the 64-shot sequence scrolls without hiding Add shot or growing its strip',async({page})=>{await open(page);const baseline=await page.locator('.builder-shot-strip').evaluate(node=>node.getBoundingClientRect().height);await page.evaluate(async()=>{const source=structuredClone(playBuilder.document);while(source.shots.length<64){const shot=structuredClone(source.shots.at(-1));shot.id=`bounded-${source.shots.length+1}`;source.shots.push(shot);}await playBuilder.action('import',JSON.stringify(source));});expect(await page.evaluate(()=>playBuilder.document.shots.length)).toBe(64);await expect(page.getByRole('button',{name:'+ Add shot',exact:true})).toBeVisible();expect(await page.locator('.builder-shot-strip').evaluate(node=>node.getBoundingClientRect().height)).toBeLessThanOrEqual(baseline+1);expect(await page.locator('.builder-sequence-scroll').evaluate(node=>node.scrollWidth>node.clientWidth)).toBe(true);});


test('pointer cancellation restores the target controls without committing a draft edit',async({page})=>{
 await open(page);await editShot(page);const before=await page.evaluate(()=>JSON.stringify(playBuilder.document));
 await page.getByRole('button',{name:'Place target on court',exact:true}).click();
 await expect(page.getByRole('button',{name:'Cancel target',exact:true})).toBeVisible();
 const point=await page.evaluate(()=>playBuilder.courtTools.project(playBuilder.selectedShot.target));
 await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+12,point.y+8);
 await page.evaluate(()=>{const tools=playBuilder.courtTools;tools.surface.dispatchEvent(new PointerEvent('pointercancel',{pointerId:tools.drag.pointer,bubbles:true}));});
 await page.mouse.up();expect(await page.evaluate(()=>playBuilder.courtTools.placing)).toBe(false);
 await expect(page.getByRole('button',{name:'Edit shot',exact:true})).toBeVisible();
 expect(await page.evaluate(()=>JSON.stringify(playBuilder.document))).toBe(before);
});
