import{test,expect}from'@playwright/test';
const open=async page=>{await page.goto('/');await page.waitForFunction(()=>window.playBuilder&&!playBuilder.busy);};
test('authors a longer rally through real controls, saves copies, and reopens named work',async({page})=>{
 await open(page);await page.getByLabel('Play title').fill('Wide serve rally');await page.getByLabel('Play title').press('Tab');
 await page.getByLabel('Target width',{exact:true}).fill('7');await page.getByLabel('Target width',{exact:true}).press('Tab');
 await page.getByRole('button',{name:'3. Drop',exact:true}).click();await page.getByLabel('Shot family',{exact:true}).selectOption('drive');
 for(let i=0;i<3;i++)await page.getByRole('button',{name:'+ Add shot',exact:true}).click();
 expect(await page.evaluate(()=>playBuilder.document.shots.length)).toBe(6);
 const id=await page.evaluate(()=>playBuilder.document.id);await page.getByRole('button',{name:'Save As',exact:true}).click();expect(await page.evaluate(()=>playBuilder.document.id)).not.toBe(id);
 await page.getByRole('button',{name:'Open',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Wide serve rally',exact:true}).click();expect(await page.evaluate(()=>playBuilder.document.id)).toBe(id);expect(await page.evaluate(()=>playBuilder.document.shots[0].target.x)).toBe(7);
 await page.getByRole('button',{name:'New Play',exact:true}).click();expect(await page.evaluate(()=>playBuilder.document.id)).not.toBe(id);expect(await page.evaluate(id=>playBuilder.store.open(id).shots.length,id)).toBe(6);
});
test('assistance is undoable and guides do not enable generated movement',async({page})=>{
 await open(page);const before=await page.evaluate(()=>JSON.stringify(playBuilder.compiled.play.steps));await page.getByRole('checkbox',{name:/Show Coverage Guides/}).check();expect(await page.evaluate(()=>playBuilder.document.assistance.autoShading)).toBe(false);expect(await page.evaluate(()=>JSON.stringify(playBuilder.compiled.play.steps))).toBe(before);
 await page.getByRole('checkbox',{name:/Auto Shading/}).check();expect(await page.evaluate(()=>JSON.stringify(playBuilder.compiled.play.steps))).not.toBe(before);await page.getByRole('button',{name:'Undo authored edit',exact:true}).click();expect(await page.evaluate(()=>playBuilder.document.assistance)).toMatchObject({autoShading:false,showGuides:true});
});
for(const[width,height]of[[1440,900],[768,1024],[1024,768],[390,844],[844,390],[320,568]])test(`default builder court and essential controls fit ${width}x${height}`,async({page})=>{
 await page.setViewportSize({width,height});await open(page);
 for(const action of ['play-pause','loop','new','templates','workspace-planner','help','import-export']){const control=page.locator(`.builder-ui [data-action="${action}"]`).first();await expect(control).toBeVisible();const box=await control.boundingBox();expect(box.x).toBeGreaterThanOrEqual(0);expect(box.y).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(width+1);expect(box.y+box.height).toBeLessThanOrEqual(height+1);}
 const canvas=await page.locator('#threeDCanvas canvas').boundingBox();expect(canvas.height).toBeGreaterThan(150);expect(canvas.width).toBeGreaterThan(250);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('emulated touch target placement at DPR2 and cancellation preserve authoring coordinates',async({browser})=>{const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,hasTouch:true});const page=await context.newPage();await open(page);await page.evaluate(()=>{playBuilder.courtTools.placing=true;playBuilder.courtTools.surface.addEventListener('pointerup',e=>window.actualTap=playBuilder.courtTools.unproject(e),{capture:true,once:true});});const p=await page.evaluate(()=>playBuilder.courtTools.project({x:6,y:37}));await page.touchscreen.tap(p.x,p.y);const target=await page.evaluate(()=>playBuilder.selectedShot.target);const actual=await page.evaluate(()=>window.actualTap);expect(target.x).toBeCloseTo(actual.x,8);expect(target.y).toBeCloseTo(actual.y,8);await page.evaluate(()=>{playBuilder.courtTools.placing=true;});await page.keyboard.press('Escape');expect(await page.evaluate(()=>playBuilder.courtTools.placing)).toBe(false);expect(await page.evaluate(()=>playBuilder.selectedShot.target)).toEqual(target);await context.close();});

test('committing a title does not swallow the immediate Save As click',async({page})=>{await open(page);await page.getByLabel('Play title').fill('First click copy');await page.getByRole('button',{name:'Save As',exact:true}).click();expect(await page.evaluate(()=>playBuilder.document.title)).toBe('First click copy — copy');expect(await page.evaluate(()=>playBuilder.store.list().length)).toBe(2);});

test('builder help returns keyboard focus without changing the draft',async({page})=>{await open(page);const before=await page.evaluate(()=>JSON.stringify(playBuilder.document));const help=page.getByRole('button',{name:'Help',exact:true});await page.getByLabel('Play title').focus();await help.click();await expect(page.locator('#infoModal')).toHaveClass(/active/);await page.keyboard.press('Escape');await expect(help).toBeFocused();expect(await page.evaluate(()=>JSON.stringify(playBuilder.document))).toBe(before);});
test('200 percent text keeps transport and compact scene controls accessible',async({page})=>{await page.setViewportSize({width:390,height:844});await open(page);await page.evaluate(()=>{document.documentElement.style.fontSize='200%';playBuilder.render();});await expect(page.locator('body')).toHaveClass(/builder-large-text/);const play=page.getByRole('button',{name:'Play',exact:true});await play.scrollIntoViewIfNeeded();await expect(play).toBeVisible();expect(await page.evaluate(()=>document.querySelector('.builder-ui').scrollWidth<=innerWidth)).toBe(true);});

test('example file import is explicit and leaves the authoring controls usable',async({page})=>{await page.setViewportSize({width:844,height:390});await open(page);await page.getByRole('button',{name:'Import / Export',exact:true}).click();await page.getByLabel('Choose JSON file').setInputFiles('docs/builder/examples/eight-shot-drive-drop.json');await expect(page.getByLabel('JSON backup')).toHaveValue(/eight-shot-drive-drop/);await page.getByRole('button',{name:'Import JSON',exact:true}).click();expect(await page.evaluate(()=>playBuilder.document.shots.length)).toBe(8);expect(await page.evaluate(()=>playBuilder.message)).not.toContain('malformed');const add=page.getByRole('button',{name:'+ Add shot',exact:true});await expect(add).toBeEnabled();const box=await add.boundingBox();expect(box.x+box.width).toBeLessThanOrEqual(844);await add.click();expect(await page.evaluate(()=>playBuilder.document.shots.length)).toBe(9);const family=page.getByLabel('Shot family',{exact:true});await family.scrollIntoViewIfNeeded();await family.selectOption('drop');expect(await page.evaluate(()=>playBuilder.selectedShot.family)).toBe('drop');});

test('undoing an appended shot retains a valid editable selection',async({page})=>{await open(page);await page.getByRole('button',{name:'+ Add shot',exact:true}).click();await page.getByRole('button',{name:'Undo authored edit',exact:true}).click();expect(await page.evaluate(()=>Boolean(playBuilder.selectedShot))).toBe(true);await page.getByLabel('Target width',{exact:true}).fill('6');await page.getByLabel('Target width',{exact:true}).press('Tab');expect(await page.evaluate(()=>playBuilder.selectedShot.target.x)).toBe(6);});
